<a href="https://colab.research.google.com/github/Kiran-Pokhrel-91/Data/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Pandas Cheat Sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)

[Python for Data Analsis](https://wesmckinney.com/book/pandas-basics)

[Conda Cheat Sheet](https://docs.conda.io/projects/conda/en/4.6.0/_downloads/52a95608c49671267e40c689e0bc00ca/conda-cheatsheet.pdf)

In [ ]:
import pandas as pd
import seaborn as sns
import numpy as np

In [ ]:
nepaldf=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Pandas/nepal population.csv")
nepaldf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 753 entries, 0 to 752
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   District                753 non-null    object
 1   Local Level Name        753 non-null    object
 2   Total family number     753 non-null    int64
 3   Total household number  753 non-null    int64
 4   Total population        753 non-null    int64
 5   Total Male              753 non-null    int64
 6   Total Female            753 non-null    int64
dtypes: int64(5), object(2)
memory usage: 41.3+ KB

In [ ]:
nepaldf.head()

,District,Local Level Name,Total family number,Total household number,Total population,Total Male,Total Female
0,Taplejung,Aathrai Tribeni Rural Municipality,2869,2735,12288,6005,6283
1,Taplejung,Maiwakhola Rural Municipality,2275,2178,10365,5264,5101
2,Taplejung,Meringden Rural Municipality,2683,2528,12040,6181,5859
3,Taplejung,Mikwakhola Rural Municipality,1862,1792,7991,4000,3991
4,Taplejung,Phaktanglung Rural Municipality,2864,2700,11925,6239,5686

In [ ]:
nepaldf.describe()

,Total family number,Total household number,Total population,Total Male,Total Female
count,753.000000,753.000000,753.000000,753.000000,753.000000
mean,8976.723772,7493.590969,38612.204515,18842.814077,19769.390438
std,12986.552238,8401.892705,49904.377212,24891.928559,25046.362147
min,125.000000,125.000000,398.000000,170.000000,228.000000
25%,4036.000000,3653.000000,16768.000000,8115.000000,8553.000000
50%,5896.000000,5195.000000,25508.000000,12248.000000,13010.000000
75%,9510.000000,8151.000000,44929.000000,22100.000000,23068.000000
max,231714.000000,105649.000000,845767.000000,431501.000000,414266.000000

# 1 - Make Dataframe

In [ ]:
pd.DataFrame({'fname':['Kiran','Kishor','Nikhil','Pawan'],
              'lname':['Pokhrel','Pokhrel','Bhusal','Pandey'],
              'age':[16,17,18,19]})

arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
pd.DataFrame(arr1)

arr2 = np.array(np.random.randn(4,8))
pd.DataFrame(arr2)

,0,1,2,3,4,5,6,7
0,0.011650,1.290955,0.599356,-0.668098,-1.023011,-1.077092,0.004809,1.333858
1,-0.003616,1.132048,1.474150,0.198592,-0.066334,0.243138,-1.665222,1.853693
2,0.231424,1.216172,0.387876,0.281761,-1.055410,0.528260,1.336643,0.333563
3,-0.693195,0.350324,0.420246,0.756755,0.632032,-1.242375,-0.346095,-1.464104

# 2 - How to rename Columns?

In [ ]:
mydf=pd.DataFrame({'fname':['Kiran','Kishor','Nikhil','Pawan'],
              'lname':['Pokhrel','Pokhrel','Bhusal','Pandey'],
              'age':[16,17,18,19]})
mydf

    fname    lname  age
0   Kiran  Pokhrel   16
1  Kishor  Pokhrel   17
2  Nikhil   Bhusal   18
3   Pawan   Pandey   19

In [ ]:
# renaming columns
mydf.rename(columns={'fname':'first_name','lname':'last_name'},inplace=True)
mydf

  first_name last_name  age
0      Kiran   Pokhrel   16
1     Kishor   Pokhrel   17
2     Nikhil    Bhusal   18
3      Pawan    Pandey   19

In [ ]:
# We have to type all the columns and change there.
mydf.columns=['First_name','Last_name','age']
mydf

  First_name Last_name  age
0      Kiran   Pokhrel   16
1     Kishor   Pokhrel   17
2     Nikhil    Bhusal   18
3      Pawan    Pandey   19

In [ ]:
# replacing chracter
mydf.columns=mydf.columns.str.replace('_','-')
mydf

  First-name Last-name  age
0      Kiran   Pokhrel   16
1     Kishor   Pokhrel   17
2     Nikhil    Bhusal   18
3      Pawan    Pandey   19

In [ ]:
# Add prefix and suffix
mydf=mydf.add_prefix('[')
mydf=mydf.add_suffix(']')
mydf

  [First-name] [Last-name]  [age]
0        Kiran     Pokhrel     16
1       Kishor     Pokhrel     17
2       Nikhil      Bhusal     18
3        Pawan      Pandey     19

In [ ]:
# Serring to defult
mydf.columns=['fname','lname','age']
mydf

    fname    lname  age
0   Kiran  Pokhrel   16
1  Kishor  Pokhrel   17
2  Nikhil   Bhusal   18
3   Pawan   Pandey   19

# 3 - Reverse Row order

In [ ]:
titanicdf =sns.load_dataset("titanic") # getting data
titanicdf

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
titanicdf.iloc[::-1].head() # though the row is reveersed but index is starting 890-0

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True

In [ ]:
# resetting index to 0
titanicdf.iloc[::-1].reset_index(drop=True).head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True
1,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
2,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
3,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
4,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True

# 4 - Reverse Column order

In [ ]:
titanicdf

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
titanicdf.iloc[:,::-1].head()

,alone,alive,embark_town,deck,adult_male,who,class,embarked,fare,parch,sibsp,age,sex,pclass,survived
0,False,no,Southampton,NaN,True,man,Third,S,7.2500,0,1,22.0,male,3,0
1,False,yes,Cherbourg,C,False,woman,First,C,71.2833,0,1,38.0,female,1,1
2,True,yes,Southampton,NaN,False,woman,Third,S,7.9250,0,0,26.0,female,3,1
3,False,yes,Southampton,C,False,woman,First,S,53.1000,0,1,35.0,female,1,1
4,True,no,Southampton,NaN,True,man,Third,S,8.0500,0,0,35.0,male,3,0

In [ ]:
# Recersing both rows and columns and resettind index to zero
titanicdf.iloc[::-1,::-1].reset_index(drop=True).head()

,alone,alive,embark_town,deck,adult_male,who,class,embarked,fare,parch,sibsp,age,sex,pclass,survived
0,True,no,Queenstown,NaN,True,man,Third,Q,7.75,0,0,32.0,male,3,0
1,True,yes,Cherbourg,C,True,man,First,C,30.00,0,0,26.0,male,1,1
2,False,no,Southampton,NaN,False,woman,Third,S,23.45,2,1,NaN,female,3,0
3,True,yes,Southampton,B,False,woman,First,S,30.00,0,0,19.0,female,1,1
4,True,no,Southampton,NaN,True,man,Second,S,13.00,0,0,27.0,male,2,0

# 5 - Select Column by data type

In [ ]:
titanicdf.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [ ]:
# titanicdf.select_dtypes("number").head()
titanicdf.select_dtypes(include=["number","bool"]).head()

   survived  pclass   age  sibsp  parch     fare  adult_male  alone
0         0       3  22.0      1      0   7.2500        True  False
1         1       1  38.0      1      0  71.2833       False  False
2         1       3  26.0      0      0   7.9250       False   True
3         1       1  35.0      1      0  53.1000       False  False
4         0       3  35.0      0      0   8.0500        True   True

In [ ]:
titanicdf.select_dtypes(exclude=["number","bool"]).head()

      sex embarked  class    who deck  embark_town alive
0    male        S  Third    man  NaN  Southampton    no
1  female        C  First  woman    C    Cherbourg   yes
2  female        S  Third  woman  NaN  Southampton   yes
3  female        S  First  woman    C  Southampton   yes
4    male        S  Third    man  NaN  Southampton    no

# 6 - Convert string to numners

In [ ]:
mydf=pd.DataFrame({'fname':['Kiran','Kishor','Nikhil','Pawan'],
              'lname':['Pokhrel','Pokhrel','Bhusal','Pandey'],
              'age':['16','17','18','19']})
mydf

    fname    lname age
0   Kiran  Pokhrel  16
1  Kishor  Pokhrel  17
2  Nikhil   Bhusal  18
3   Pawan   Pandey  19

In [ ]:
mydf=mydf.astype({'age':'int64'})
mydf.dtypes

fname    object
lname    object
age       int64
dtype: object

# 7 - Reduce dataframe size

In [ ]:
titanicdf.shape

(891, 15)

In [ ]:
titanicdf.sample(frac=0.1).shape

(89, 15)

# 8 - Split dataframe into two subset

In [ ]:
titanicdf.shape

(891, 15)

In [ ]:
# getting random 50% data of titanicdf
sample_1 = titanicdf.sample(frac=0.5,random_state=1)
sample_1.shape

(446, 15)

In [ ]:
# removing/dropping sample_1 from from titanicdf to get remaning data
sample_2 = titanicdf.drop(sample_1.index)
sample_2.shape

(445, 15)

In [ ]:
445+446

891

In [ ]:
combined_df= pd.concat([sample_1,sample_1])
combined_df.shape

(892, 15)

# 9 - Filter datasets

In [ ]:
titanicdf.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
titanicdf.sex.unique(), titanicdf.embarked.unique()

(array(['male', 'female'], dtype=object),
 array(['S', 'C', 'Q', nan], dtype=object))

In [ ]:
titanicdf[(titanicdf.sex=="female")].head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

In [ ]:
titanicdf[(titanicdf.sex=="female") & (titanicdf.embarked=="S")].head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True

# 10 - Filtterin by large catogaries

In [ ]:
titanicdf.who.value_counts()

who
man      537
woman    271
child     83
Name: count, dtype: int64

In [ ]:
titanicdf.age.value_counts().nlargest(5)

age
24.0    30
22.0    27
18.0    26
28.0    25
30.0    25
Name: count, dtype: int64

# 11 - Splitting string into multiple columns

In [ ]:
data = {
    'name': ['John Doe', 'Alice Mary', 'Raj Kumar', 'Emily Smith', 'Michael Smith'],
    'city': ['New York', 'Los Angeles', 'Delhi', 'London', 'Chicago'],
    'phoneno': ['1234567890', '9876543210', '1122334455', '5566778899', '9988776655']
}
datadf = pd.DataFrame(data)
datadf

            name         city     phoneno
0       John Doe     New York  1234567890
1     Alice Mary  Los Angeles  9876543210
2      Raj Kumar        Delhi  1122334455
3    Emily Smith       London  5566778899
4  Michael Smith      Chicago  9988776655

In [ ]:
datadf[["fname","lname"]]=datadf.name.str.split(" ",expand=True)
datadf

            name         city     phoneno    fname  lname
0       John Doe     New York  1234567890     John    Doe
1     Alice Mary  Los Angeles  9876543210    Alice   Mary
2      Raj Kumar        Delhi  1122334455      Raj  Kumar
3    Emily Smith       London  5566778899    Emily  Smith
4  Michael Smith      Chicago  9988776655  Michael  Smith

In [ ]:
# regining data according to need
datadf=datadf[["fname","lname","city","phoneno"]]
datadf

     fname  lname         city     phoneno
0     John    Doe     New York  1234567890
1    Alice   Mary  Los Angeles  9876543210
2      Raj  Kumar        Delhi  1122334455
3    Emily  Smith       London  5566778899
4  Michael  Smith      Chicago  9988776655

# 12 - Arrigate by multiple groups

In [ ]:
titanicdf.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
titanicdf.groupby('who').count()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,deck,embark_town,alive,alone
who,,,,,,,,,,,,,,
child,83,83,83,83,83,83,83,83,83,83,13,83,83,83
man,537,537,537,413,537,537,537,537,537,537,99,537,537,537
woman,271,271,271,218,271,271,271,269,271,271,91,269,271,271

In [ ]:
titanicdf.groupby(['alive','sex','who']).count()

                    survived  pclass  age  sibsp  parch  fare  embarked  \
alive sex    who
no    female child        15      15   15     15     15    15        15
             woman        66      66   49     66     66    66        66
      male   child        19      19   19     19     19    19        19
             man         449     449  341    449    449   449       449
yes   female child        28      28   28     28     28    28        28
             woman       205     205  169    205    205   205       203
      male   child        21      21   21     21     21    21        21
             man          88      88   72     88     88    88        88

                    class  adult_male  deck  embark_town  alone
alive sex    who
no    female child     15          15     2           15     15
             woman     66          66     4           66     66
      male   child     19          19     0           19     19
             man      449         449    61          449    449
yes   female child     28          28     4           28     28
             woman    205         205    87          203    205
      male   child     21          21     7           21     21
             man       88          88    38           88     88

# 13 - Selecting specific rows and columns

In [ ]:
titanicdf.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [ ]:
titanicdf.describe().iloc[['min','max'],['age','fare']]
# or
# titanicdf.describe().iloc[[3,5],[2,5]]

IndexError: .iloc requires numeric indexers, got ['min' 'max']

# 14 - creating bins

In [ ]:
titanicdf["new_age"]=pd.cut(titanicdf.age, bins=[0,18,25,49,99], labels=["child","young","adult","old"])
titanicdf.head()

# 15 - CONVERTING ONE SET OF VALUE TO ANOTHER

In [ ]:
titanicdf["sex_num"]=titanicdf.sex.map({'male':'0','female':'1'})
titanicdf.head()

In [ ]:
titanicdf["enmarked_num"]=titanicdf.embarked.factorize()[0]
titanicdf.head(8)

In [ ]:
# Edited